import type { Tool, Category } from '@/types/tools';

export const TOOLS: Tool[] = [
  // Image Tools
  {
    slug: 'image-compressor',
    title: 'Image Compressor',
    description: 'Compress images without losing quality.',
    icon: '🖼️',
    category: 'Image Tools',
    keywords: ['compress', 'image', 'jpg', 'png', 'webp'],
  },
  {
    slug: 'image-resizer',
    title: 'Image Resizer',
    description: 'Resize images to any size while preserving aspect ratio.',
    icon: '📐',
    category: 'Image Tools',
    keywords: ['resize', 'image', 'dimensions'],
  },
  {
    slug: 'image-cropper',
    title: 'Image Cropper',
    description: 'Crop images with precision and save the result instantly.',
    icon: '✂️',
    category: 'Image Tools',
    keywords: ['crop', 'image', 'edit'],
  },
  {
    slug: 'jpg-to-png',
    title: 'JPG to PNG',
    description: 'Convert JPG images to PNG format in seconds.',
    icon: '🔄',
    category: 'Image Tools',
    keywords: ['convert', 'jpg', 'png'],
  },
  {
    slug: 'png-to-jpg',
    title: 'PNG to JPG',
    description: 'Convert PNG images to JPG for smaller file sizes.',
    icon: '🔄',
    category: 'Image Tools',
    keywords: ['convert', 'png', 'jpg'],
  },
  {
    slug: 'image-to-base64',
    title: 'Image to Base64',
    description: 'Convert images into Base64 strings for embedding in code.',
    icon: '🔤',
    category: 'Image Tools',
    keywords: ['base64', 'image', 'encode'],
  },
  {
    slug: 'image-metadata',
    title: 'Image Metadata Viewer',
    description: 'View EXIF and other metadata embedded in image files.',
    icon: '📊',
    category: 'Image Tools',
    keywords: ['metadata', 'exif', 'image'],
  },
  {
    slug: 'watermark-image',
    title: 'Watermark Image Tool',
    description: 'Add text or image watermarks to photos with ease.',
    icon: '💧',
    category: 'Image Tools',
    keywords: ['watermark', 'image', 'privacy'],
  },

  // Text Tools
  {
    slug: 'word-counter',
    title: 'Word Counter',
    description: 'Count words, characters, sentences, and more.',
    icon: '📝',
    category: 'Text Tools',
    keywords: ['word', 'count', 'text'],
  },
  {
    slug: 'character-counter',
    title: 'Character Counter',
    description: 'Count characters with or without spaces.',
    icon: '🔤',
    category: 'Text Tools',
    keywords: ['character', 'count', 'text'],
  },
  {
    slug: 'case-converter',
    title: 'Case Converter',
    description: 'Convert text to upper, lower, title, snake and camel case.',
    icon: 'Aa',
    category: 'Text Tools',
    keywords: ['case', 'text', 'convert'],
  },
  {
    slug: 'remove-duplicates',
    title: 'Remove Duplicate Lines',
    description: 'Remove duplicate lines from your text quickly.',
    icon: '🗑️',
    category: 'Text Tools',
    keywords: ['duplicate', 'text', 'clean'],
  },
  {
    slug: 'random-text',
    title: 'Random Text Generator',
    description: 'Generate random text snippets and lorem ipsum content.',
    icon: '🎲',
    category: 'Text Tools',
    keywords: ['random', 'text', 'lorem'],
  },
  {
    slug: 'lorem-ipsum-generator',
    title: 'Lorem Ipsum Generator',
    description: 'Generate placeholder Lorem Ipsum text with custom length.',
    icon: '📄',
    category: 'Text Tools',
    keywords: ['lorem', 'ipsum', 'placeholder'],
  },
  {
    slug: 'text-sorter',
    title: 'Text Sorter',
    description: 'Sort lines of text alphabetically or numerically.',
    icon: '🔤',
    category: 'Text Tools',
    keywords: ['sort', 'text', 'lines'],
  },
  {
    slug: 'text-reverser',
    title: 'Text Reverser',
    description: 'Reverse text or entire lines in your content.',
    icon: '↩️',
    category: 'Text Tools',
    keywords: ['reverse', 'text', 'flip'],
  },

  // Developer Tools
  {
    slug: 'json-formatter',
    title: 'JSON Formatter',
    description: 'Format and validate JSON data instantly.',
    icon: '💻',
    category: 'Developer Tools',
    keywords: ['json', 'format', 'validate', 'minify'],
  },
  {
    slug: 'base64-encoder',
    title: 'Base64 Encoder/Decoder',
    description: 'Encode and decode text to/from Base64.',
    icon: '🔤',
    category: 'Developer Tools',
    keywords: ['base64', 'encode', 'decode'],
  },
  {
    slug: 'url-encoder',
    title: 'URL Encoder/Decoder',
    description: 'Encode and decode URLs and query strings.',
    icon: '🌐',
    category: 'Developer Tools',
    keywords: ['url', 'encode', 'decode'],
  },
  {
    slug: 'url-decoder',
    title: 'URL Decoder',
    description: 'Decode URL-encoded strings for easy reading.',
    icon: '🔓',
    category: 'Developer Tools',
    keywords: ['url', 'decode', 'percent-encoding'],
  },
  {
    slug: 'html-formatter',
    title: 'HTML Formatter',
    description: 'Format and beautify HTML code snippets.',
    icon: '🏷️',
    category: 'Developer Tools',
    keywords: ['html', 'format', 'beautify'],
  },
  {
    slug: 'css-minifier',
    title: 'CSS Minifier',
    description: 'Minify CSS to reduce file size and speed up loading.',
    icon: '💾',
    category: 'Developer Tools',
    keywords: ['css', 'minify', 'compress'],
  },
  {
    slug: 'js-minifier',
    title: 'JS Minifier',
    description: 'Minify JavaScript to make it smaller and faster.',
    icon: '⚡',
    category: 'Developer Tools',
    keywords: ['js', 'minify', 'compress'],
  },
  {
    slug: 'regex-tester',
    title: 'Regex Tester',
    description: 'Test and debug regular expressions quickly.',
    icon: '🧪',
    category: 'Developer Tools',
    keywords: ['regex', 'test', 'pattern'],
  },

  // Calculators
  {
    slug: 'age-calculator',
    title: 'Age Calculator',
    description: 'Calculate your age from your birth date.',
    icon: '🎂',
    category: 'Calculators',
    keywords: ['age', 'calculator', 'birthdate'],
  },
  {
    slug: 'emi-calculator',
    title: 'EMI Calculator',
    description: 'Calculate monthly EMI payments for loans.',
    icon: '💳',
    category: 'Calculators',
    keywords: ['emi', 'loan', 'payments'],
  },
  {
    slug: 'loan-interest-calculator',
    title: 'Loan Interest Calculator',
    description: 'Estimate interest and total payments for loans.',
    icon: '📈',
    category: 'Calculators',
    keywords: ['loan', 'interest', 'calculator'],
  },
  {
    slug: 'percentage-calculator',
    title: 'Percentage Calculator',
    description: 'Quickly calculate percentages and percent changes.',
    icon: '％',
    category: 'Calculators',
    keywords: ['percentage', 'calculator', 'percent'],
  },
  {
    slug: 'profit-margin-calculator',
    title: 'Profit Margin Calculator',
    description: 'Compute profit margin and markup for products.',
    icon: '💰',
    category: 'Calculators',
    keywords: ['profit', 'margin', 'calculator'],
  },
  {
    slug: 'discount-calculator',
    title: 'Discount Calculator',
    description: 'Calculate sale prices and savings from discounts.',
    icon: '🏷️',
    category: 'Calculators',
    keywords: ['discount', 'price', 'sale'],
  },
  {
    slug: 'gst-calculator',
    title: 'GST Calculator',
    description: 'Calculate GST amounts and totals for transactions.',
    icon: '🧾',
    category: 'Calculators',
    keywords: ['gst', 'tax', 'calculator'],
  },
  {
    slug: 'salary-calculator',
    title: 'Salary Calculator',
    description: 'Estimate take-home pay after taxes and deductions.',
    icon: '💼',
    category: 'Calculators',
    keywords: ['salary', 'paycheck', 'calculator'],
  },

  // Generators
  {
    slug: 'qr-code-generator',
    title: 'QR Code Generator',
    description: 'Generate QR codes from text and URLs.',
    icon: '📱',
    category: 'Generators',
    keywords: ['qr', 'code', 'barcode', 'scan'],
  },
  {
    slug: 'password-generator',
    title: 'Password Generator',
    description: 'Create strong, random passwords instantly.',
    icon: '🔒',
    category: 'Generators',
    keywords: ['password', 'secure', 'random'],
  },
  {
    slug: 'random-number-generator',
    title: 'Random Number Generator',
    description: 'Generate random numbers within a range.',
    icon: '🎲',
    category: 'Generators',
    keywords: ['random', 'number', 'generator'],
  },
  {
    slug: 'random-name-generator',
    title: 'Random Name Generator',
    description: 'Generate random names for characters and projects.',
    icon: '👤',
    category: 'Generators',
    keywords: ['name', 'random', 'generator'],
  },
  {
    slug: 'uuid-generator',
    title: 'UUID Generator',
    description: 'Generate unique UUIDs for identifiers.',
    icon: '🆔',
    category: 'Generators',
    keywords: ['uuid', 'unique', 'identifier'],
  },
  {
    slug: 'fake-address-generator',
    title: 'Fake Address Generator',
    description: 'Generate realistic-looking fake addresses.',
    icon: '🏠',
    category: 'Generators',
    keywords: ['address', 'fake', 'generator'],
  },
  {
    slug: 'slug-generator',
    title: 'Slug Generator',
    description: 'Create URL-friendly slugs from text.',
    icon: '🔗',
    category: 'Generators',
    keywords: ['slug', 'url', 'seo'],
  },

  // Converters
  {
    slug: 'unit-converter',
    title: 'Unit Converter',
    description: 'Convert between common units like length, weight and volume.',
    icon: '⚖️',
    category: 'Converters',
    keywords: ['unit', 'convert', 'length', 'weight'],
  },
  {
    slug: 'time-converter',
    title: 'Time Converter',
    description: 'Convert between time zones and formats.',
    icon: '⏱️',
    category: 'Converters',
    keywords: ['time', 'convert', 'zone'],
  },
  {
    slug: 'temperature-converter',
    title: 'Temperature Converter',
    description: 'Convert between Celsius, Fahrenheit and Kelvin.',
    icon: '🌡️',
    category: 'Converters',
    keywords: ['temperature', 'convert', 'celsius', 'fahrenheit'],
  },
  {
    slug: 'currency-converter',
    title: 'Currency Converter',
    description: 'Convert currencies using live exchange rates.',
    icon: '💱',
    category: 'Converters',
    keywords: ['currency', 'convert', 'exchange'],
  },
  {
    slug: 'binary-to-decimal',
    title: 'Binary to Decimal Converter',
    description: 'Convert binary numbers to decimal.',
    icon: '🔢',
    category: 'Converters',
    keywords: ['binary', 'decimal', 'convert'],
  },
  {
    slug: 'decimal-to-binary',
    title: 'Decimal to Binary Converter',
    description: 'Convert decimal numbers to binary.',
    icon: '🔢',
    category: 'Converters',
    keywords: ['decimal', 'binary', 'convert'],
  },
  {
    slug: 'text-to-ascii',
    title: 'Text to ASCII Converter',
    description: 'Convert text to ASCII codes.',
    icon: '🔡',
    category: 'Converters',
    keywords: ['text', 'ascii', 'convert'],
  },
  {
    slug: 'ascii-to-text',
    title: 'ASCII to Text Converter',
    description: 'Convert ASCII codes back to readable text.',
    icon: '🔡',
    category: 'Converters',
    keywords: ['ascii', 'text', 'convert'],
  },

  // Design Tools
  {
    slug: 'color-palette-generator',
    title: 'Color Palette Generator',
    description: 'Generate harmonious color palettes instantly.',
    icon: '🎨',
    category: 'Design Tools',
    keywords: ['color', 'palette', 'design'],
  },
  {
    slug: 'gradient-generator',
    title: 'Gradient Generator',
    description: 'Create beautiful gradients and copy CSS instantly.',
    icon: '🌈',
    category: 'Design Tools',
    keywords: ['gradient', 'css', 'design'],
  },
  {
    slug: 'random-color-generator',
    title: 'Random Color Generator',
    description: 'Generate random colors with hex and RGB values.',
    icon: '🎨',
    category: 'Design Tools',
    keywords: ['color', 'random', 'hex'],
  },
];

export const CATEGORIES: Category[] = [
  {
    slug: 'image-tools',
    name: 'Image Tools',
    description: 'Compress, resize, convert and edit images online.',
    tools: TOOLS.filter((tool) => tool.category === 'Image Tools').map((tool) => tool.slug),
    icon: '🖼️',
  },
  {
    slug: 'text-tools',
    name: 'Text Tools',
    description: 'Text utilities for formatting, editing and analyzing content.',
    tools: TOOLS.filter((tool) => tool.category === 'Text Tools').map((tool) => tool.slug),
    icon: '📝',
  },
  {
    slug: 'developer-tools',
    name: 'Developer Tools',
    description: 'Developer tools for formatting, converting and testing code.',
    tools: TOOLS.filter((tool) => tool.category === 'Developer Tools').map((tool) => tool.slug),
    icon: '💻',
  },
  {
    slug: 'calculators',
    name: 'Calculators',
    description: 'Useful calculators for finance, age, and more.',
    tools: TOOLS.filter((tool) => tool.category === 'Calculators').map((tool) => tool.slug),
    icon: '🧮',
  },
  {
    slug: 'generators',
    name: 'Generators',
    description: 'Generate passwords, QR codes, UUIDs and more.',
    tools: TOOLS.filter((tool) => tool.category === 'Generators').map((tool) => tool.slug),
    icon: '🧩',
  },
  {
    slug: 'converters',
    name: 'Converters',
    description: 'Convert between units, formats, and encodings.',
    tools: TOOLS.filter((tool) => tool.category === 'Converters').map((tool) => tool.slug),
    icon: '🔁',
  },
  {
    slug: 'design-tools',
    name: 'Design Tools',
    description: 'Design-friendly tools for colors, gradients and palettes.',
    tools: TOOLS.filter((tool) => tool.category === 'Design Tools').map((tool) => tool.slug),
    icon: '🎨',
  },
];

export function getToolBySlug(slug: string) {
  return TOOLS.find((tool) => tool.slug === slug);
}

export function getCategoryBySlug(slug: string) {
  return CATEGORIES.find((category) => category.slug === slug);
}
